# basic options
title: My First Github Blog
author: Fernandoplato
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  Fernandoplato

# Build settings
markdown: kramdown
theme: minima
